### ISSUE TITLE
Can't install Rdiscount on Windows machine with international characters in computer name

### ISSUE THREAD

**Issue by maximkoo** [davidfstr/rdiscount#125]
Hi,

I can't install rdiscount versions 2.07 ... 2.1.8 on my Windows 7 64. I need it for installing Octopress, but I always get the following error

-------------------
c:\Users\Maxim\Documents\maximkoo.github.com>gem install rdiscount -v '2.1.8'
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing rdiscount:
        ERROR: Failed to build gem native extension.

    C:/RailsInstaller/Ruby2.1.0/bin/ruby.exe extconf.rb
checking for random()... no
checking for srandom()... no
checking for rand()... yes
checking for srand()... yes
checking size of unsigned long... 4
checking size of unsigned int... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/RailsInstaller/Ruby2.1.0/bin/ruby
        --with-rdiscount-dir
        --without-rdiscount-dir
        --with-rdiscount-include
        --without-rdiscount-include=${rdiscount-dir}/include
        --with-rdiscount-lib
        --without-rdiscount-lib=${rdiscount-dir}/lib
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:408:in `popen': Invalid argum
ent - ruby_setenv(LOGONSERVER) (Errno::EINVAL)
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:408:in `block in
 xpopen'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:401:in `xpopen'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:704:in `try_cons
tant'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:1309:in `block i
n check_sizeof'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:918:in `block in
 checking_for'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:351:in `block (2
 levels) in postpone'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:351:in `block in
 postpone'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:347:in `postpone
'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:917:in `checking
_for'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/mkmf.rb:1308:in `check_s
izeof'
        from extconf.rb:11:in `block in sized_int'
        from extconf.rb:11:in `each'
        from extconf.rb:11:in `find'
        from extconf.rb:11:in `sized_int'
        from extconf.rb:16:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1
.0/gems/rdiscount-2.1.8 for inspection.
Results logged to C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/extensions/x86
-mingw32/2.1.0/rdiscount-2.1.8/gem_make.out

Please help.

**Comment by davidfstr** [comment]
Life has gotten extremely busy for me recently, so it will probably take me another week or two to get around to looking at this. -- My best suggestion would be to try installing RDiscount in a clean Windows 7 VM to see if there are any environmental issues with your main dev machine.

**Comment by maximkoo** [comment]
Hi, David!

It looks like I've found the solution myself. My home computer has name 'Maxim-ПК', including two cyrillic symbols, that probably caused an error in LOGONSERVER environment variable. I changed the name for 'Maxim-PC', and RDiscount has been installed perfectly. 

Hope my solution will be useful to others.

Всем спасибо за внимание.

**Comment by davidfstr** [comment]
How bizarre. I wouldn't expect the RDiscount or the MinGW toolchain to care about the LOGONSERVER variable. Just goes to show that most software just doesn't do Unicode correctly...

**Comment by davidfstr** [comment]
Hmm. I can't seem to rename my Windows computer to the name that you provided. It always pastes underscores for international characters.

Since you've already found a workaround, I'll close this.
