### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by ghost** [davidfstr/rdiscount#130]
Hi.

I do not know if LaTeX is officially supported, but that would be great to have it.

Look at the following formula:

```
$$
M = \left\\{ c \in  \mathbb{C} | \lim_{n\to\infty} Z_n \neq \infty \right\\}
\begin{align}
& Z_0 = c \\\
& Z\_{n+1} = Z\_n\^2 + c
\end{align}
$$
```

I had to add a couple of `\` to make it work properly. For example, the first two `_` are replaced by the `<em>` tag without the `\`. So anything between `$$` should be kept as-is.

Note: I use Octopress and the basic configuration.

Ar.

**Comment by davidfstr** [comment]
Hey @Arn-O, please bring this request to @Orc at #Orc/discount, which is the underlying Markdown parser that RDiscount wraps.

**Comment by Arn-O** [comment]
For reference: https://github.com/Orc/discount/issues/128

**Comment by davidfstr** [comment]
LaTeX support is now in Discount 2.2.0, so just need to bump the embedded version of Discount in RDiscount. Tracking in #135

**Comment by davidfstr** [comment]
Hi @Arn-O , are you still interested in some kind of LaTeX passthru or other kind of support?

I am looking for more information about what specific behavior is desired. Your current example passes thru (R)Discount 2.2.0 with barely any modification. See output here: https://gist.github.com/davidfstr/2a68b736fb829401d6ccd5d69a8ccaf8

What exactly were you planning to do with LaTeX formatting once it was dumped into the HTML page? Unless you're doing something fancy, it won't automatically render to the expected typographical output.

**Comment by davidfstr** [comment]
I notice from Discount's documentation that the Discount LaTeX support looks like:

```
If configured with the --with-latex option, text wrapped in $$…$$, \[…\], and \(…\)
is passed unchanged (except for encoding <, >, and &) to the output for processing
by a LaTeX renderer.
```

Does this seem reasonable? (Anyone who cares about LaTeX feel free to comment.)

**Comment by davidfstr** [comment]
CC @leonsim

**Comment by leonsim** [comment]
@davidfstr Yes, this is reasonable. text wrapped in `\[...\]` and `\(...\)` is passed unchanged and in this way the equations are handed over to MathJax which will do the typographical work by javascript.

**Comment by Arn-O** [comment]
Hi. Yes, still interested but I don't say that it is critical to me. What I need is to have all text wrapped by ``$$...$$`` unchanged at all. As explained by @leonsim MathJax will take care of the formatting.

**Comment by leonsim** [comment]
@Arn-O `$$...$$` feature is also added. I wrote tests to make sure it works: <https://github.com/Orc/discount/pull/140>

**Comment by Arn-O** [comment]
All is clear from my end and happy to see it deployed!

**Comment by davidfstr** [comment]
Okay. Makes sense. Now I just need to find some more time rupees to finish off the release.

**Comment by davidfstr** [comment]
Darn. Looks like the LaTeX passthrough behavior for \\[ and \\] conflicts with standard Markdown behavior.

In standard Markdown (as defined by the semi-official Perl MarkdownTest_1.0.3):
* \\[ -> \[

But in the current Discount LaTeX passthrough implementation:
* \\[ -> \\[

**If the Discount LaTeX passthrough were altered to only accept the delimiter $$, would that be sufficient for common LaTeX formatting needs?**

As mentioned above, \\[ conflicts with standard Markdown. And I suspect \\( may as well.

**Comment by Orc** [comment]
This does not surprise me in the least;  *many* of the aftermarket features tend to stomp on the edges of standard markdown, and my implementation of LaTeX passthrough only falls back to the proper behavior if the offending paragraph does not contain a matching close paren or bracket.

I can disable \\( & \\[ LaTeX escapes by checking for MKD_STRICT, but MKD_STRICT is a blunt instrument designed for standards compatibility.     But I run my regression tests with -ftabstop, -fnopants (and -f1.0 for the 1.0.3 testsuite) and, at least after tidy, don't see any failures on the 1.0.3 testsuite?  Which test fails for you?

**Comment by leonsim** [comment]
I read Markdown specs once more, but not find definition about `\[`. I searched `MarkdownTest_1.0.3` and it's originally from `redcarpet` (The markdown dialect used by Github), right? Must we obey that tests? 

Only accepting the delimiter `$$` is not sufficient because there are two modes in MathJax
- inline mode : wrapped with `\(...\)`
- block mode : wrapped with `\[...\]` or `$$...$$`

**Comment by Orc** [comment]
Wait, your MarkdownTest_1.0.3 includes a reference to a different markdown implementation?  I grepped my copy of 1.0.3 and found no reference to redcarpet?

**Comment by leonsim** [comment]
Check this <https://github.com/davidfstr/rdiscount/blob/master/test/MarkdownTest_1.0.3/Tests/Backslash%20escapes.text> I think @davidfstr means this test.

**Comment by davidfstr** [comment]
Here's the specific test failure: https://gist.github.com/davidfstr/f5fa8516ae284cdc95e565d082c98c37

If you checkout my "latex" branch and run the following commands, you should get the same output:
* gem build rdiscount.gemspec
* gem install rdiscount-*.gem
* rake test

My copy of MarkdownTest_1.0.3 contains no textual reference to redcarpet. A long time ago when I investigated where this test suite came from, it appeared to be an extension to the original Perl tests for Gruber's Markdown (MarkdownTest_1.0).

**Comment by Orc** [comment]
Okay, I do have that test and discount handles it properly?   (My regression tester is:

~~~~~~~~~~
#! /bin/sh


if make test ; then
    MARKDOWN=`pwd`/markdown; export MARKDOWN
    DYLD_LIBRARY_PATH=`pwd`; export DYLD_LIBRARY_PATH
    make -C ~/MarkdownTest_1.0.3
    make -C ~/MarkdownTest_1.0
fi
~~~~~~~~~~~~

Which runs the 1.0.3 makefile:

~~~~~~~~~~~~
test:
	MALLOC_OPTIONS=AJVX MARKDOWN_FLAGS=0x20004 ./MarkdownTest.pl --tidy --script=$${MARKDOWN:-$$HOME/Src/discount/markdown}

test2:
	MALLOC_OPTIONS=AJVX MARKDOWN_FLAGS=0x20004 ./MarkdownTest.pl --tidy --script=/tmp/discount-1.1.4/markdown
~~~~~~~~~~~~

(test2 is wildly obsolete, obviously, but the test script doesn't care about it.)

**Comment by davidfstr** [comment]
Sounds like some more investigation is required.

My "markdown" is configured with:
* ./configure.sh --with-latex

With my copy of MarkdownTest_1.0.3, I can run the following:
* discount/markdown < test/MarkdownTest_1.0.3/Tests/Links\,\ reference\ style.text

This yields an document with \\[this\\] where the expected HTML has \[this\].

Perhaps our versions of MarkdownTest_1.0.3 have diverged somehow?

**Comment by Orc** [comment]
~~~~~~
27c27
< <p>Backslashing should suppress \[this] and [this\].</p>
---
> <p>Backslashing should suppress [this] and [this].</p>
~~~~~~

That text is not in my copy of MarkdownTest 1.0.3.     That's /really/ bad; it means that someone has fucked with the testsuite without bumping the version number.    That's a good test, but MarkdownTest should have had the goddamn version number bumped when the tests were changed (not blaming you; blaming the author of your version -- I grabbed my copy of MarkdownTest 1.0.3 /years/ ago and have not touched anything inside the Tests directory)

**Comment by Orc** [comment]
I just grabbed a copy of the original MarkdownTest_1.0.3 from daringfireball (dated 2007) and it does _not_ include the "Backslashing should suppress ..." test.  You've got a bogus version of 1.0.3

**Comment by davidfstr** [comment]
Ah ha. Time to do some digging to figure out how my 1.0.3 tests got changed. That's definitely a no-no without a version bump.

**Comment by davidfstr** [comment]
I'm moving the discussion RE: MarkdownTest_1.0.3 to a different ticket (https://github.com/davidfstr/rdiscount/issues/136), since it isn't directly related to introducing LaTeX support (which is the primary subject of this issue).

**Comment by davidfstr** [comment]
Regardless of the provenance of the current MarkdownTest_1.0.3 tests, they have specified the RDiscount behavior since the early days, so I am reluctant to break them in the default configuration of RDiscount.

To avoid breaking the prior specified behavior of RDiscount under a default configuration, LaTeX support would need to be opt-in rather than by default.

Currently LaTeX support can be enabled only by adding a *configure-time* flag to the underlying Discount. Therefore there is no way to opt-in (or opt-out) at runtime. It is either baked in as off or on.

So my current position is that a patch would need to be introduced to Discount to convert the LaTeX support to be a runtime option rather than a configure-time option. When that is done, I can introduce a extension flag to RDiscount that selectively enables LaTeX at runtime.

**Comment by Orc** [comment]
Yeah, but I'm running out of flag bits  (I have 30 right now so that leaves me only two -- three if I move an internal control flag into a different variable --  more dynamically flaggable things before I run out of space and have to start stomping all over the published interface to fit more) :-(
