### ISSUE TITLE
MarkdownTest_1.0.3 tests have diverged from the original source?

### ISSUE THREAD

**Issue by davidfstr** [davidfstr/rdiscount#136]
Orc indicates that the copy of MarkdownTest_1.0.3 in RDiscount has diverged from the original version at Daring Fireball.

This issue serves to track that investigation.

**Comment by davidfstr** [comment]
@Orc I'm not able to locate the MarkdownTest_1.0.3 on Daring Fireball that you referenced. Could you give me a link to the version you're using? Preferably the referencing HTML page if applicable.

**Comment by davidfstr** [comment]
FYI: The version of MarkdownTest_1.0.3 that RDiscount currently uses was committed on May 30, 2008 and was never changed subsequently.

**Comment by Orc** [comment]
From the [discount home page](http://www.pell.portland.or.us/~orc/Code/discount/), I link to [a post on the old markdown discussion group](http://six.pairlist.net/pipermail/markdown-discuss/2006-June/000079.html), which links to [the 1.0.3 test suite](http://daringfireball.net/projects/downloads/MarkdownTest_1.0.3.tbz) tarball.

**Comment by Orc** [comment]
The md5 checksum of that tarball (or at least of the copy I downloaded a couple of days ago when your 1.0.3alike reared its head) is:

~~~~
MD5 (/Users/orc/Downloads/MarkdownTest_1.0.3.tbz) = 76f925f3ae8dcf4394098be8dbe3d227
~~~~

**Comment by davidfstr** [comment]
@rtomayko, sorry to bother you, but do you recall where you downloaded MarkdownTest_1.0.3 from when you committed it to the RDiscount project on May 30, 2008?

**Comment by davidfstr** [comment]
Closing due to lack of response.

It seems that the origin of the original MarkdownTest_1.0.3 has been lost to the sands of time.
