### ISSUE TITLE
filter_styles not working

### ISSUE THREAD

**Issue by veesahni** [davidfstr/rdiscount#149]
Looks like issue #38 is back.

Given the following:

```ruby
content = "Hello *github*
<style type='text/css' media='screen'>
p{margin:5px}
</style>
"
puts RDiscount.new(content).to_html
```

Expected output (since filter_styles was not enabled):
```html
<p>Hello <em>github</em></p>
<style type='text/css' media='screen'>
p{margin:5px}
</style>
```

Actual output (with RDiscount ```2.2.0.2```):
```html
<p>Hello <em>github</em></p>
```

**Comment by fliiiix** [comment]
@veesahni have a look at the PR I made, and give feedback

**Comment by davidfstr** [comment]
RDiscount 2.2.7.1 has been released with this fix
