### ISSUE TITLE
Docs seem to be broken

### ISSUE THREAD

**Issue by fliiiix** [davidfstr/rdiscount#150]
For example linked from the readme: https://rdoc.info/github/davidfstr/rdiscount/master/RDiscount

![image](https://user-images.githubusercontent.com/1682954/192149400-efc259e1-0fe9-493a-94d7-e6e41c8f5bde.png)

**Comment by davidfstr** [comment]
I reentered the GitHub HTTPS url (rather than HTTP), and it appears to have regenerated the docs appropriately.
